import React from 'react';
import { useNavigate } from 'react-router-dom';
import { IndianRupee, Calendar, TrendingUp, MonitorSmartphone, Wallet, CreditCard, Activity } from 'lucide-react';
import { useRevenue } from '../../mock/revenueContext';
import { useMachine } from '../../mock/machineContext';
import { useOrg } from '../../mock/orgContext';
import { useAuth } from '../../app/authContext';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { StatCard } from '../../components/dashboard/StatCard';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/Table';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

export function DistributorRevenueDashboard() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { transactions, getMachineAggregation } = useRevenue();
  const { machines } = useMachine();
  const { partners } = useOrg();
  
  // Distributor machines filter
  const myMachines = machines.filter(m => m.distributorId === user?.id);
  const myMachineIds = new Set(myMachines.map(m => m.id));

  const myTransactions = transactions.filter(t => myMachineIds.has(t.machineId) && t.paymentStatus === 'successful');

  const totalRevenue = myTransactions.reduce((acc, curr) => acc + curr.amount, 0);
  
  const now = new Date();
  const todayRevenue = myTransactions.filter(t => {
    const d = new Date(t.transactionDate);
    return d.getDate() === now.getDate() && d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  }).reduce((acc, curr) => acc + curr.amount, 0);

  const thisMonthRevenue = myTransactions.filter(t => {
    const d = new Date(t.transactionDate);
    return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  }).reduce((acc, curr) => acc + curr.amount, 0);

  const activeRevenueMachines = new Set(myTransactions.map(t => t.machineId)).size;

  const chartData = Array.from({ length: 7 }).map((_, i) => {
    const d = new Date();
    d.setDate(d.getDate() - (6 - i));
    const dayStr = d.toLocaleDateString('en-US', { weekday: 'short' });
    const dayRev = myTransactions.filter(t => {
      const td = new Date(t.transactionDate);
      return td.getDate() === d.getDate() && td.getMonth() === d.getMonth();
    }).reduce((acc, curr) => acc + curr.amount, 0);
    return { name: dayStr, revenue: dayRev };
  });

  const getPartnerName = (id: string | null) => {
    if (!id) return '-';
    return partners.find(p => p.id === id)?.businessName || id;
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Machine Revenue</h1>
        <p className="text-sm text-slate-500">Track gross revenue generated by your assigned machines.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard title="Gross Revenue" value="₹2,45,300" icon={IndianRupee} trend={{ value: 12, isPositive: true }} />
        <StatCard title="Distributor Share" value="₹1,47,180" icon={Wallet} trend={{ value: 8, isPositive: true }} />
        <StatCard title="Total Transactions" value="754" icon={CreditCard} trend={{ value: 15, isPositive: true }} />
        <StatCard title="Avg Ticket Size" value="₹325" icon={Activity} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Revenue Trend (Last 7 Days)</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={chartData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                  <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b' }} />
                  <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b' }} tickFormatter={(val) => `₹${val}`} />
                  <Tooltip formatter={(value) => [`₹${value}`, 'Revenue']} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                  <Line type="monotone" dataKey="revenue" stroke="#4f46e5" strokeWidth={3} dot={{ r: 4, fill: '#4f46e5', strokeWidth: 0 }} activeDot={{ r: 6 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Partner Breakdown</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {partners.filter(p => p.distributorId === user?.id).map(p => {
                const partnerMachines = myMachines.filter(m => m.partnerId === p.id);
                const partnerRev = myTransactions.filter(t => partnerMachines.some(m => m.id === t.machineId)).reduce((acc, curr) => acc + curr.amount, 0);
                
                if (partnerRev === 0) return null;

                return (
                  <div key={p.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100">
                    <div>
                      <p className="text-sm font-medium text-slate-900">{p.businessName}</p>
                      <p className="text-xs text-slate-500">{partnerMachines.length} machines deployed</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-bold text-slate-900">₹{partnerRev.toLocaleString()}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Machine-Wise Revenue</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Machine Code</TableHead>
                <TableHead>Deployed Partner</TableHead>
                <TableHead className="text-right">Today</TableHead>
                <TableHead className="text-right">This Month</TableHead>
                <TableHead className="text-right">Total Revenue</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {myMachines.map(m => {
                const agg = getMachineAggregation(m.id);
                if (agg.totalRevenue === 0) return null; 
                
                return (
                  <TableRow key={m.id}>
                    <TableCell className="font-mono font-medium text-slate-900">{m.machineCode}</TableCell>
                    <TableCell className="text-sm">{getPartnerName(m.partnerId)}</TableCell>
                    <TableCell className="text-right font-medium text-slate-700">₹{agg.todayRevenue.toLocaleString()}</TableCell>
                    <TableCell className="text-right font-medium text-slate-700">₹{agg.thisMonthRevenue.toLocaleString()}</TableCell>
                    <TableCell className="text-right font-bold text-slate-900">₹{agg.totalRevenue.toLocaleString()}</TableCell>
                  </TableRow>
                );
              })}
              {myMachines.length === 0 && (
                <TableRow><TableCell colSpan={5} className="text-center text-slate-500 py-4">No revenue data available.</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

    </div>
  );
}
