import React from 'react';
import { IndianRupee, Calendar, TrendingUp, MonitorSmartphone } from 'lucide-react';
import { useRevenue } from '../../mock/revenueContext';
import { useMachine } from '../../mock/machineContext';
import { useAuth } from '../../app/authContext';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { StatCard } from '../../components/dashboard/StatCard';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/Table';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

export function PartnerRevenueDashboard() {
  const { user } = useAuth();
  const { transactions, getMachineAggregation } = useRevenue();
  const { machines } = useMachine();
  
  // Partner machines filter
  const myMachines = machines.filter(m => m.partnerId === user?.id);
  const myMachineCodes = new Set(myMachines.map(m => m.machineCode));

  const myTransactions = transactions.filter(t => myMachineCodes.has(t.machineId) && t.paymentStatus === 'successful');

  const totalRevenue = myTransactions.reduce((acc, curr) => acc + curr.amount, 0);
  
  const now = new Date();
  const todayRevenue = myTransactions.filter(t => {
    const d = new Date(t.transactionDate);
    return d.getDate() === now.getDate() && d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  }).reduce((acc, curr) => acc + curr.amount, 0);

  const thisMonthRevenue = myTransactions.filter(t => {
    const d = new Date(t.transactionDate);
    return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  }).reduce((acc, curr) => acc + curr.amount, 0);

  const activeRevenueMachines = new Set(myTransactions.map(t => t.machineId)).size;

  const chartData = Array.from({ length: 7 }).map((_, i) => {
    const d = new Date();
    d.setDate(d.getDate() - (6 - i));
    const dayStr = d.toLocaleDateString('en-US', { weekday: 'short' });
    const dayRev = myTransactions.filter(t => {
      const td = new Date(t.transactionDate);
      return td.getDate() === d.getDate() && td.getMonth() === d.getMonth();
    }).reduce((acc, curr) => acc + curr.amount, 0);
    return { name: dayStr, revenue: dayRev };
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Revenue Tracking</h1>
        <p className="text-sm text-slate-500">Track gross revenue generated by machines at your locations.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard title="Total Gross Revenue" value={`₹${totalRevenue.toLocaleString('en-IN')}`} icon={IndianRupee} />
        <StatCard title="Today's Revenue" value={`₹${todayRevenue.toLocaleString('en-IN')}`} icon={Calendar} />
        <StatCard title="This Month" value={`₹${thisMonthRevenue.toLocaleString('en-IN')}`} icon={TrendingUp} />
        <StatCard title="Active Machines" value={activeRevenueMachines} icon={MonitorSmartphone} />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Revenue Trend (Last 7 Days)</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={chartData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b' }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#64748b' }} tickFormatter={(val) => `₹${val}`} />
                <Tooltip formatter={(value) => [`₹${value}`, 'Revenue']} contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                <Line type="monotone" dataKey="revenue" stroke="#4f46e5" strokeWidth={3} dot={{ r: 4, fill: '#4f46e5', strokeWidth: 0 }} activeDot={{ r: 6 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Machine-Wise Revenue</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Machine Code</TableHead>
                <TableHead>Location</TableHead>
                <TableHead className="text-right">Today</TableHead>
                <TableHead className="text-right">This Month</TableHead>
                <TableHead className="text-right">Total Revenue</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {myMachines.map(m => {
                const agg = getMachineAggregation(m.machineCode);
                if (agg.totalRevenue === 0) return null; 
                
                return (
                  <TableRow key={m.id}>
                    <TableCell className="font-mono font-medium text-slate-900">{m.machineCode}</TableCell>
                    <TableCell className="text-sm">{m.location}</TableCell>
                    <TableCell className="text-right font-medium text-slate-700">₹{agg.todayRevenue.toLocaleString()}</TableCell>
                    <TableCell className="text-right font-medium text-slate-700">₹{agg.thisMonthRevenue.toLocaleString()}</TableCell>
                    <TableCell className="text-right font-bold text-slate-900">₹{agg.totalRevenue.toLocaleString()}</TableCell>
                  </TableRow>
                );
              })}
              {myMachines.length === 0 && (
                <TableRow><TableCell colSpan={5} className="text-center text-slate-500 py-4">No revenue data available.</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

