import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Lock } from 'lucide-react';
import { useSettlement } from '../../mock/settlementContext';
import { useOrg } from '../../mock/orgContext';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/Table';
import { SettlementStatusBadge } from '../../components/ui/StatusBadges';

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export function PartnerSettlementDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { partnerSettlements } = useSettlement();
  const { distributors } = useOrg();

  const settlement = partnerSettlements.find(s => s.id === id);

  if (!settlement) {
    return (
      <div className="text-center py-12">
        <h2 className="text-xl font-bold text-slate-700">Settlement not found</h2>
        <Button className="mt-4" onClick={() => navigate('/partner/settlements')}>Back to Settlements</Button>
      </div>
    );
  }

  const distributor = distributors.find(d => d.id === settlement.distributorId);
  const totalGross = settlement.machineBreakdown.reduce((acc, curr) => acc + (curr.grossRevenue || 0), 0);
  const isLocked = ['approved', 'payment_pending', 'paid', 'closed'].includes(settlement.status);

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <button 
          onClick={() => navigate('/partner/settlements')}
          className="p-2 hover:bg-slate-100 rounded-full text-slate-500"
        >
          <ArrowLeft className="h-5 w-5" />
        </button>
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold text-slate-900">{settlement.settlementNumber}</h1>
            <SettlementStatusBadge status={settlement.status} />
            {isLocked && (
              <span className="flex items-center text-xs font-medium text-slate-500 bg-slate-100 px-2 py-1 rounded-full">
                <Lock className="w-3 h-3 mr-1" /> Locked
              </span>
            )}
          </div>
          <p className="text-sm text-slate-500">
            {MONTHS[settlement.periodMonth - 1]} {settlement.periodYear} • Generated by {distributor?.businessName || 'Distributor'}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
        <Card>
          <CardContent className="pt-6">
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Step 1</p>
            <p className="text-sm font-medium text-slate-700 mt-2">Machine Gross Revenue</p>
            <p className="text-xl font-bold text-slate-900 mt-1">₹{totalGross.toLocaleString()}</p>
          </CardContent>
        </Card>
        
        <Card className="bg-slate-50 border-dashed">
          <CardContent className="pt-6">
            <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Step 2</p>
            <p className="text-sm font-medium text-slate-700 mt-2">Distributor Entitlement</p>
            <p className="text-xl font-bold text-slate-700 mt-1">₹{settlement.eligibleRevenue.toLocaleString()}</p>
            <p className="text-xs text-slate-500 mt-1">From Company</p>
          </CardContent>
        </Card>
        
        <Card className="bg-indigo-50 border-indigo-100">
          <CardContent className="pt-6">
            <p className="text-xs font-medium text-indigo-400 uppercase tracking-wider">Step 3</p>
            <p className="text-sm font-medium text-indigo-900 mt-2">My Share Agreement</p>
            <p className="text-xl font-bold text-indigo-700 mt-1">{settlement.partnerSharePercent}%</p>
            <p className="text-xs text-indigo-500 mt-1">Of Distributor share</p>
          </CardContent>
        </Card>
        
        <Card className="bg-emerald-50 border-emerald-100 lg:col-span-1 shadow-sm border-2">
          <CardContent className="pt-6 relative">
            <p className="text-xs font-medium text-emerald-500 uppercase tracking-wider">Step 4</p>
            <p className="text-sm font-medium text-emerald-900 mt-2">My Final Entitlement</p>
            <p className="text-2xl font-bold text-emerald-700 mt-1">₹{settlement.partnerPayableAmount.toLocaleString()}</p>
            {settlement.status === 'paid' && (
              <CheckCircle2 className="absolute top-4 right-4 w-6 h-6 text-emerald-600" />
            )}
          </CardContent>
        </Card>

        <Card className="bg-slate-100 opacity-75">
          <CardContent className="pt-6">
            <p className="text-xs font-medium text-slate-400 uppercase tracking-wider">Step 5</p>
            <p className="text-sm font-medium text-slate-600 mt-2">Distributor Retained</p>
            <p className="text-xl font-bold text-slate-700 mt-1">₹{settlement.distributorRetainedAmount.toLocaleString()}</p>
            <p className="text-xs text-slate-500 mt-1">Kept by Distributor</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Machine-Level Breakdown</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Machine Code</TableHead>
                <TableHead className="text-right">Machine Gross Revenue</TableHead>
                <TableHead className="text-right">Distributor Entitlement</TableHead>
                <TableHead className="text-right">My Share ({settlement.partnerSharePercent}%)</TableHead>
                <TableHead className="text-right">Distributor Retained</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {settlement.machineBreakdown.map(mb => {
                // Partner settlement machine breakdown structure:
                // mb.companyShareAmount = Distributor Retained
                // mb.distributorShareAmount = Partner Payable (My Share)
                // The base Eligible = Distributor Retained + Partner Payable
                const distEntitlement = mb.companyShareAmount + mb.distributorShareAmount; 
                
                return (
                  <TableRow key={mb.machineId}>
                    <TableCell className="font-mono text-sm">{mb.machineCode}</TableCell>
                    <TableCell className="text-right font-medium text-slate-500">₹{mb.grossRevenue?.toLocaleString()}</TableCell>
                    <TableCell className="text-right font-medium text-slate-700">₹{distEntitlement.toLocaleString()}</TableCell>
                    <TableCell className="text-right font-bold text-indigo-600">₹{mb.distributorShareAmount.toLocaleString()}</TableCell>
                    <TableCell className="text-right text-slate-400">₹{mb.companyShareAmount.toLocaleString()}</TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
