import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../app/authContext';
import { useSettlement } from '../../mock/settlementContext';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/Table';
import { Button } from '../../components/ui/Button';
import { SettlementStatusBadge } from '../../components/ui/StatusBadges';
import { Eye } from 'lucide-react';

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export function PartnerSettlementsList() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { partnerSettlements } = useSettlement();

  const mySettlements = partnerSettlements.filter(s => s.partnerId === user?.id);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Settlements</h1>
        <p className="text-sm text-slate-500">View your revenue settlements generated by your Distributor.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Settlement History</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Settlement ID</TableHead>
                <TableHead>Period</TableHead>
                <TableHead className="text-right">Eligible Revenue</TableHead>
                <TableHead className="text-right">My Share</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {mySettlements.map(s => (
                <TableRow key={s.id}>
                  <TableCell className="font-mono text-sm">{s.settlementNumber}</TableCell>
                  <TableCell>{MONTHS[s.periodMonth - 1]} {s.periodYear}</TableCell>
                  <TableCell className="text-right font-medium">₹{s.eligibleRevenue.toLocaleString()}</TableCell>
                  <TableCell className="text-right text-indigo-600 font-bold">₹{s.partnerPayableAmount.toLocaleString()}</TableCell>
                  <TableCell><SettlementStatusBadge status={s.status} /></TableCell>
                  <TableCell className="text-right">
                    <Button variant="outline" size="sm" onClick={() => navigate(`/partner/settlements/${s.id}`)}>
                      <Eye className="h-4 w-4 mr-2" /> View
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
              {mySettlements.length === 0 && (
                <TableRow><TableCell colSpan={6} className="text-center py-6 text-slate-500">No settlements generated yet.</TableCell></TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
